name: Static Code Check

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pytest
        run: pip install pytest
        
      - name: Run tests
        run: pytest tests/ --disable-warnings
      
      - name: Run custom summary
        if: always()  
        run: python tests/run_tests_summary.py

